### ISSUE TITLE
Storybook deploy

### ISSUE THREAD

**Issue by kubk** [XeleneStudio/TelegramUI#1]
Hi, congratulations on the initial release! 👍 It would be nice to see the UI kit's Storybook deployed somewhere, for example on GitHub Pages, so people could try out the UI kit without the need to install it first.

**Comment by kubk** [comment]
Sorry, I haven't noticed it in the comment: https://tgui.xelene.me/?path=/story/blocks-badge--dot

It'd be nice if you made it visible from the repository page 👍

**Comment by mainsmirnov** [comment]
We'll definitely add it, thank you
