### ISSUE TITLE
Example for TabsList

### ISSUE THREAD

**Issue by sitenativedev** [XeleneStudio/TelegramUI#10]
Component not import from @xelene/tgui (like some others).
If import :

import {TabsList} from "@xelene/tgui/dist/components/Navigation/TabsList/TabsList.js";
import {TabsItem} from "@xelene/tgui/dist/components/Navigation/TabsList/components/TabsItem/TabsItem.js";

Result:

<img width="361" alt="image" src="https://github.com/XeleneStudio/TelegramUI/assets/87825983/c68d8322-aa61-4429-8d68-7d9f1816a35e">

**Comment by mainsmirnov** [comment]
Thank you, we fixed this issue in version 2.0.5 https://github.com/XeleneStudio/TelegramUI/commit/2ce0fb49304ae9d211094b5047e55c18150e95a6.
