### ISSUE TITLE
Segmented control doesn't support dark mode

### ISSUE THREAD

**Issue by kubk** [XeleneStudio/TelegramUI#2]
The issue is reproducible on both iOS and Android.

URL: https://tgui.xelene.me/?path=/story/navigation-segmentedcontrol--playground&globals=theme:dark

<img width="496" alt="Screenshot 2024-02-14 at 15 31 30" src="https://github.com/XeleneStudio/TelegramUI/assets/22447849/d769966c-743f-418c-aef6-a0d3c483455a">
<img width="530" alt="Screenshot 2024-02-14 at 15 31 35" src="https://github.com/XeleneStudio/TelegramUI/assets/22447849/28c19bfb-3e40-4870-a8de-3edbca13d703">

**Comment by mainsmirnov** [comment]
Thank you, we will take a look

**Comment by mainsmirnov** [comment]
Thank you, fixed here https://github.com/XeleneStudio/TelegramUI/commit/9fed6081398db78f0f10a959f4a66cfd0001a14f
