### ISSUE TITLE
Wrong textarea placeholder color

### ISSUE THREAD

**Issue by sitenativedev** [XeleneStudio/TelegramUI#8]
<img width="369" alt="image" src="https://github.com/XeleneStudio/TelegramUI/assets/87825983/00ad728a-3996-47ec-9e64-6e2b957d1f63">

The textarea placeholder text color must match the imput placeholder text color

**Comment by mainsmirnov** [comment]
Thank you, we fixed this issue in version 2.0.5 https://github.com/XeleneStudio/TelegramUI/commit/2ce0fb49304ae9d211094b5047e55c18150e95a6
