### ISSUE TITLE
Invalid loading state

### ISSUE THREAD

**Issue by sitenativedev** [XeleneStudio/TelegramUI#9]
<img width="1067" alt="image" src="https://github.com/XeleneStudio/TelegramUI/assets/87825983/364afdf6-bc00-4a68-a0f9-6aabb017f03d">

For button, mode bezeled, invalid spinner color. Label not hide.

**Comment by mainsmirnov** [comment]
Thank you, we fixed this issue in version 2.0.5 https://github.com/XeleneStudio/TelegramUI/commit/2ce0fb49304ae9d211094b5047e55c18150e95a6.
